export enum IconsEnum {
  "EXPAND" = "EXPAND",
  "STAR" = "STAR",
  "CALENDAR" = "CALENDAR",
  "PIN" = "PIN",
  "SQUARE" = "SQUARE",
  "TRIANGLE" = "TRIANGLE",
  "EXCLAMATION" = "EXCLAMATION",
  "PROJECT_BOARD" = "PROJECT_BOARD",
}