export enum IconsEnum {
  "TRIANGLE" = "TRIANGLE",
  "SQUARE" = "SQUARE",
  "CIRCLE_CHECK" = "CIRCLE_CHECK",
  "CIRCLE_FULL" = "CIRCLE_FULL",
  "CIRCLE_OUTLINE" = "CIRCLE_OUTLINE",
  "STAR" = "STAR",
  "CALENDAR" = "CALENDAR",
  "EXCLAMATION" = "EXCLAMATION",
  "CATEGORY" = "CATEGORY"
}